development:
  jetty_path: "/usr/local/jetty"
  solr_data_dir: "/Users/t/src/ruby/solrsan_example_solr/solr-data"
  solr_server_url: "http://localhost:2222/solr"
test:
  jetty_path: "/usr/local/jetty"
  solr_data_dir: "/Users/t/src/ruby/solrsan_example_solr/solr-data"
  solr_server_url: "http://localhost:2222/solr"
production:
  jetty_path: "/usr/local/jetty"
  solr_data_dir: "/data/search/appname-data"
  solr_server_url: "http://localhost:8080/solr"

